# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Team")

model.instance <- Team$new()

test_that("abbreviation", {
  # tests for the property `abbreviation` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`abbreviation`, "EXPECTED_RESULT")
})

test_that("division", {
  # tests for the property `division` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`division`, "EXPECTED_RESULT")
})

test_that("league", {
  # tests for the property `league` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`league`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("team_name", {
  # tests for the property `team_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`team_name`, "EXPECTED_RESULT")
})

test_that("venue", {
  # tests for the property `venue` (Venue)

  # uncomment below to test the property 
  #expect_equal(model.instance$`venue`, "EXPECTED_RESULT")
})

