# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test State")

model.instance <- State$new()

test_that("on_1b", {
  # tests for the property `on_1b` (character)
  # True iff there is a runner on 1st base.

  # uncomment below to test the property 
  #expect_equal(model.instance$`on_1b`, "EXPECTED_RESULT")
})

test_that("on_2b", {
  # tests for the property `on_2b` (character)
  # True iff there is a runner on 2nd base.

  # uncomment below to test the property 
  #expect_equal(model.instance$`on_2b`, "EXPECTED_RESULT")
})

test_that("on_3b", {
  # tests for the property `on_3b` (character)
  # True iff there is a runner on 3rd base.

  # uncomment below to test the property 
  #expect_equal(model.instance$`on_3b`, "EXPECTED_RESULT")
})

test_that("inning", {
  # tests for the property `inning` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`inning`, "EXPECTED_RESULT")
})

test_that("outs", {
  # tests for the property `outs` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`outs`, "EXPECTED_RESULT")
})

test_that("top", {
  # tests for the property `top` (character)
  # True if in the top half of the inning.

  # uncomment below to test the property 
  #expect_equal(model.instance$`top`, "EXPECTED_RESULT")
})

test_that("bat_score", {
  # tests for the property `bat_score` (integer)
  # Batting team score

  # uncomment below to test the property 
  #expect_equal(model.instance$`bat_score`, "EXPECTED_RESULT")
})

test_that("fld_score", {
  # tests for the property `fld_score` (integer)
  # Batting team score

  # uncomment below to test the property 
  #expect_equal(model.instance$`fld_score`, "EXPECTED_RESULT")
})

test_that("bat_lineup_order", {
  # tests for the property `bat_lineup_order` (integer)
  # Lineup position (1-9) of the batting team.  Used only for game simulations

  # uncomment below to test the property 
  #expect_equal(model.instance$`bat_lineup_order`, "EXPECTED_RESULT")
})

test_that("fld_lineup_order", {
  # tests for the property `fld_lineup_order` (integer)
  # Lineup position (1-9) of the batting team.  Used only for game simulations

  # uncomment below to test the property 
  #expect_equal(model.instance$`fld_lineup_order`, "EXPECTED_RESULT")
})

test_that("pitch_number", {
  # tests for the property `pitch_number` (integer)
  # Current pitcher&#39;s pitch count at the beginning of the plate appearance

  # uncomment below to test the property 
  #expect_equal(model.instance$`pitch_number`, "EXPECTED_RESULT")
})

test_that("frame_runs_scored", {
  # tests for the property `frame_runs_scored` (integer)
  # Number of runs scored in the current half inning so far

  # uncomment below to test the property 
  #expect_equal(model.instance$`frame_runs_scored`, "EXPECTED_RESULT")
})

