# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Atmosphere")

model.instance <- Atmosphere$new()

test_that("venue", {
  # tests for the property `venue` (Venue)

  # uncomment below to test the property 
  #expect_equal(model.instance$`venue`, "EXPECTED_RESULT")
})

test_that("home_team", {
  # tests for the property `home_team` (Team)

  # uncomment below to test the property 
  #expect_equal(model.instance$`home_team`, "EXPECTED_RESULT")
})

test_that("temperature", {
  # tests for the property `temperature` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`temperature`, "EXPECTED_RESULT")
})

