# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BodyGetGameSimGameSimPost")

model.instance <- BodyGetGameSimGameSimPost$new()

test_that("game", {
  # tests for the property `game` (Game)

  # uncomment below to test the property 
  #expect_equal(model.instance$`game`, "EXPECTED_RESULT")
})

test_that("start_state", {
  # tests for the property `start_state` (State)

  # uncomment below to test the property 
  #expect_equal(model.instance$`start_state`, "EXPECTED_RESULT")
})

