# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Matchup")

model.instance <- Matchup$new()

test_that("batter", {
  # tests for the property `batter` (Player)

  # uncomment below to test the property 
  #expect_equal(model.instance$`batter`, "EXPECTED_RESULT")
})

test_that("pitcher", {
  # tests for the property `pitcher` (Player)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pitcher`, "EXPECTED_RESULT")
})

test_that("atmosphere", {
  # tests for the property `atmosphere` (Atmosphere)

  # uncomment below to test the property 
  #expect_equal(model.instance$`atmosphere`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (State)

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

