# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Lineup")

model.instance <- Lineup$new()

test_that("lineup", {
  # tests for the property `lineup` (array[LineupPos])

  # uncomment below to test the property 
  #expect_equal(model.instance$`lineup`, "EXPECTED_RESULT")
})

