# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LineupPos")

model.instance <- LineupPos$new()

test_that("player", {
  # tests for the property `player` (Player)

  # uncomment below to test the property 
  #expect_equal(model.instance$`player`, "EXPECTED_RESULT")
})

test_that("position", {
  # tests for the property `position` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`position`, "EXPECTED_RESULT")
})

