# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Game")

model.instance <- Game$new()

test_that("home_lineup", {
  # tests for the property `home_lineup` (Lineup)

  # uncomment below to test the property 
  #expect_equal(model.instance$`home_lineup`, "EXPECTED_RESULT")
})

test_that("visit_lineup", {
  # tests for the property `visit_lineup` (Lineup)

  # uncomment below to test the property 
  #expect_equal(model.instance$`visit_lineup`, "EXPECTED_RESULT")
})

test_that("atmosphere", {
  # tests for the property `atmosphere` (Atmosphere)

  # uncomment below to test the property 
  #expect_equal(model.instance$`atmosphere`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

