# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Player")

model.instance <- Player$new()

test_that("full_name", {
  # tests for the property `full_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`full_name`, "EXPECTED_RESULT")
})

test_that("position", {
  # tests for the property `position` (character)
  # Primary position.  One of P, C, 1B, 2B, 3B, SS, LF, RF, CF, LF, DH

  # uncomment below to test the property 
  #expect_equal(model.instance$`position`, "EXPECTED_RESULT")
})

test_that("mlb_id", {
  # tests for the property `mlb_id` (integer)
  # MLB player ID

  # uncomment below to test the property 
  #expect_equal(model.instance$`mlb_id`, "EXPECTED_RESULT")
})

test_that("debut_date", {
  # tests for the property `debut_date` (character)
  # MLB debut date

  # uncomment below to test the property 
  #expect_equal(model.instance$`debut_date`, "EXPECTED_RESULT")
})

test_that("team_id", {
  # tests for the property `team_id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`team_id`, "EXPECTED_RESULT")
})

test_that("team_abbrev", {
  # tests for the property `team_abbrev` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`team_abbrev`, "EXPECTED_RESULT")
})

test_that("active", {
  # tests for the property `active` (character)
  # True if player is currently active

  # uncomment below to test the property 
  #expect_equal(model.instance$`active`, "EXPECTED_RESULT")
})

test_that("bat_side", {
  # tests for the property `bat_side` (character)
  # One of L, R, S

  # uncomment below to test the property 
  #expect_equal(model.instance$`bat_side`, "EXPECTED_RESULT")
})

test_that("pitch_hand", {
  # tests for the property `pitch_hand` (character)
  # One of L, R, S

  # uncomment below to test the property 
  #expect_equal(model.instance$`pitch_hand`, "EXPECTED_RESULT")
})

test_that("birth_country", {
  # tests for the property `birth_country` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`birth_country`, "EXPECTED_RESULT")
})

test_that("birth_date", {
  # tests for the property `birth_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`birth_date`, "EXPECTED_RESULT")
})

test_that("current_age", {
  # tests for the property `current_age` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`current_age`, "EXPECTED_RESULT")
})

test_that("photo_url", {
  # tests for the property `photo_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`photo_url`, "EXPECTED_RESULT")
})

