# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test APIsApi")

api.instance <- APIsApi$new()

test_that("GetGameSim", {
  # tests for GetGameSim
  # base path: http://localhost
  # Get Game Sim
  # @param BodyGetGameSimGameSimPost  body.get.game.sim.game.sim.post   
  # @param integer  num.sims    (optional)
  # @return [array[GameSimResults]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPaSim", {
  # tests for GetPaSim
  # base path: http://localhost
  # Get Pa Sim
  # @param array[Matchup]  matchup   
  # @param character  return.features    (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPlayers", {
  # tests for GetPlayers
  # base path: http://localhost
  # Get Players
  # @param character  name    (optional)
  # @param integer  id    (optional)
  # @param character  team.name    (optional)
  # @param integer  team.id    (optional)
  # @param array[character]  position    (optional)
  # @param integer  age.min    (optional)
  # @param integer  age.max    (optional)
  # @param array[character]  pitch.hand    (optional)
  # @param array[character]  bat.side    (optional)
  # @param character  active    (optional)
  # @return [array[Player]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTeams", {
  # tests for GetTeams
  # base path: http://localhost
  # Get Teams
  # @param character  name    (optional)
  # @return [array[Team]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetVenues", {
  # tests for GetVenues
  # base path: http://localhost
  # Get Venues
  # @param character  stadium.name    (optional)
  # @param character  team.name    (optional)
  # @return [array[Venue]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Hello", {
  # tests for Hello
  # base path: http://localhost
  # Hello
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("HelloWithKey", {
  # tests for HelloWithKey
  # base path: http://localhost
  # Hello With Key
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

