# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Venue")

model.instance <- Venue$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("home_team_abbrev", {
  # tests for the property `home_team_abbrev` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`home_team_abbrev`, "EXPECTED_RESULT")
})

test_that("home_team_id", {
  # tests for the property `home_team_id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`home_team_id`, "EXPECTED_RESULT")
})

