# Singlearity Baseball API
#
# Baseball optimization API using machine learning
#
# The version of the OpenAPI document: 0.1.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title HTTPValidationError
#'
#' @description HTTPValidationError Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field detail Detail list( \link{ValidationError} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HTTPValidationError <- R6::R6Class(
  'HTTPValidationError',
  public = list(
    `detail` = NULL,
    initialize = function(
        `detail`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (length(local.optional.var) > 0) {
        stop(paste("Unknown argument(s) in initialize of object HTTPValidationError:", paste(names(local.optional.var), collapse=", "), collapse=" "))
      }
      if (!is.null(`detail`)) {
        stopifnot(is.vector(`detail`), length(`detail`) != 0)
        sapply(`detail`, function(x) stopifnot(R6::is.R6(x)))
        self$`detail` <- `detail`
      }
    },
    toJSON = function() {
      HTTPValidationErrorObject <- list()
      if (!is.null(self$`detail`)) {
        HTTPValidationErrorObject[['detail']] <-
          lapply(self$`detail`, function(x) x$toJSON())
      }

      HTTPValidationErrorObject
    },
    fromJSON = function(HTTPValidationErrorJson) {
      HTTPValidationErrorObject <- jsonlite::fromJSON(HTTPValidationErrorJson)
      if (!is.null(HTTPValidationErrorObject$`detail`)) {
        self$`detail` <- ApiClient$new()$deserializeObj(HTTPValidationErrorObject$`detail`, "array[ValidationError]", loadNamespace("singlearity"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`detail`)) {
        sprintf(
        '"detail":
        [%s]
',
        paste(sapply(self$`detail`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(HTTPValidationErrorJson) {
      HTTPValidationErrorObject <- jsonlite::fromJSON(HTTPValidationErrorJson)
      self$`detail` <- ApiClient$new()$deserializeObj(HTTPValidationErrorObject$`detail`, "array[ValidationError]", loadNamespace("singlearity"))
      self
    }
  )
)
