# Singlearity Baseball API
#
# Baseball optimization API using machine learning
#
# The version of the OpenAPI document: 0.1.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Team
#' @description Team Class
#' @format An \code{R6Class} generator object
#' @field abbreviation Abbreviation character 
#'
#' @field division Division character 
#'
#' @field league League character 
#'
#' @field id Id integer 
#'
#' @field name Name character 
#'
#' @field team_name Team Name character 
#'
#' @field venue  \link{Venue} 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Team <- R6::R6Class(
  'Team',
  public = list(
    `abbreviation` = NULL,
    `division` = NULL,
    `league` = NULL,
    `id` = NULL,
    `name` = NULL,
    `team_name` = NULL,
    `venue` = NULL,
    initialize = function(`abbreviation`, `division`, `league`, `id`, `name`, `team_name`, `venue`, ...){
      local.optional.var <- list(...)
      if (!missing(`abbreviation`)) {
        stopifnot(is.character(`abbreviation`), length(`abbreviation`) == 1)
        self$`abbreviation` <- `abbreviation`
      }
      if (!missing(`division`)) {
        stopifnot(is.character(`division`), length(`division`) == 1)
        self$`division` <- `division`
      }
      if (!missing(`league`)) {
        stopifnot(is.character(`league`), length(`league`) == 1)
        self$`league` <- `league`
      }
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`team_name`)) {
        stopifnot(is.character(`team_name`), length(`team_name`) == 1)
        self$`team_name` <- `team_name`
      }
      if (!missing(`venue`)) {
        stopifnot(R6::is.R6(`venue`))
        self$`venue` <- `venue`
      }
    },
    toJSON = function() {
      TeamObject <- list()
      if (!is.null(self$`abbreviation`)) {
        TeamObject[['abbreviation']] <-
          self$`abbreviation`
      }
      if (!is.null(self$`division`)) {
        TeamObject[['division']] <-
          self$`division`
      }
      if (!is.null(self$`league`)) {
        TeamObject[['league']] <-
          self$`league`
      }
      if (!is.null(self$`id`)) {
        TeamObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        TeamObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`team_name`)) {
        TeamObject[['team_name']] <-
          self$`team_name`
      }
      if (!is.null(self$`venue`)) {
        TeamObject[['venue']] <-
          self$`venue`$toJSON()
      }

      TeamObject
    },
    fromJSON = function(TeamJson) {
      TeamObject <- jsonlite::fromJSON(TeamJson)
      if (!is.null(TeamObject$`abbreviation`)) {
        self$`abbreviation` <- TeamObject$`abbreviation`
      }
      if (!is.null(TeamObject$`division`)) {
        self$`division` <- TeamObject$`division`
      }
      if (!is.null(TeamObject$`league`)) {
        self$`league` <- TeamObject$`league`
      }
      if (!is.null(TeamObject$`id`)) {
        self$`id` <- TeamObject$`id`
      }
      if (!is.null(TeamObject$`name`)) {
        self$`name` <- TeamObject$`name`
      }
      if (!is.null(TeamObject$`team_name`)) {
        self$`team_name` <- TeamObject$`team_name`
      }
      if (!is.null(TeamObject$`venue`)) {
        venueObject <- Venue$new()
        venueObject$fromJSON(jsonlite::toJSON(TeamObject$venue, auto_unbox = TRUE, digits = NA))
        self$`venue` <- venueObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`abbreviation`)) {
        sprintf(
        '"abbreviation":
          "%s"
                ',
        self$`abbreviation`
        )},
        if (!is.null(self$`division`)) {
        sprintf(
        '"division":
          "%s"
                ',
        self$`division`
        )},
        if (!is.null(self$`league`)) {
        sprintf(
        '"league":
          "%s"
                ',
        self$`league`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`team_name`)) {
        sprintf(
        '"team_name":
          "%s"
                ',
        self$`team_name`
        )},
        if (!is.null(self$`venue`)) {
        sprintf(
        '"venue":
        %s
        ',
        jsonlite::toJSON(self$`venue`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TeamJson) {
      TeamObject <- jsonlite::fromJSON(TeamJson)
      self$`abbreviation` <- TeamObject$`abbreviation`
      self$`division` <- TeamObject$`division`
      self$`league` <- TeamObject$`league`
      self$`id` <- TeamObject$`id`
      self$`name` <- TeamObject$`name`
      self$`team_name` <- TeamObject$`team_name`
      self$`venue` <- Venue$new()$fromJSON(jsonlite::toJSON(TeamObject$venue, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
