# Singlearity Baseball API
#
# Baseball optimization API using machine learning
#
# The version of the OpenAPI document: 0.1.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Venue
#'
#' @description Venue Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id Id integer 
#'
#' @field name Name character 
#'
#' @field home_team_abbrev Home Team Abbrev character 
#'
#' @field home_team_id Home Team Id integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Venue <- R6::R6Class(
  'Venue',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `home_team_abbrev` = NULL,
    `home_team_id` = NULL,
    initialize = function(
        `id`, `name`, `home_team_abbrev`, `home_team_id`, ...
    ) {
      local.optional.var <- list(...)
      if (length(local.optional.var) > 0) {
        stop(paste("Unknown argument(s) in initialize of object Venue:", paste(names(local.optional.var), collapse=", "), collapse=" "))
      }
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`home_team_abbrev`)) {
        stopifnot(is.character(`home_team_abbrev`), length(`home_team_abbrev`) == 1)
        self$`home_team_abbrev` <- `home_team_abbrev`
      }
      if (!missing(`home_team_id`)) {
        stopifnot(is.numeric(`home_team_id`), length(`home_team_id`) == 1)
        self$`home_team_id` <- `home_team_id`
      }
    },
    toJSON = function() {
      VenueObject <- list()
      if (!is.null(self$`id`)) {
        VenueObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        VenueObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`home_team_abbrev`)) {
        VenueObject[['home_team_abbrev']] <-
          self$`home_team_abbrev`
      }
      if (!is.null(self$`home_team_id`)) {
        VenueObject[['home_team_id']] <-
          self$`home_team_id`
      }

      VenueObject
    },
    fromJSON = function(VenueJson) {
      VenueObject <- jsonlite::fromJSON(VenueJson)
      if (!is.null(VenueObject$`id`)) {
        self$`id` <- VenueObject$`id`
      }
      if (!is.null(VenueObject$`name`)) {
        self$`name` <- VenueObject$`name`
      }
      if (!is.null(VenueObject$`home_team_abbrev`)) {
        self$`home_team_abbrev` <- VenueObject$`home_team_abbrev`
      }
      if (!is.null(VenueObject$`home_team_id`)) {
        self$`home_team_id` <- VenueObject$`home_team_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`home_team_abbrev`)) {
        sprintf(
        '"home_team_abbrev":
          "%s"
                ',
        self$`home_team_abbrev`
        )},
        if (!is.null(self$`home_team_id`)) {
        sprintf(
        '"home_team_id":
          %d
                ',
        self$`home_team_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VenueJson) {
      VenueObject <- jsonlite::fromJSON(VenueJson)
      self$`id` <- VenueObject$`id`
      self$`name` <- VenueObject$`name`
      self$`home_team_abbrev` <- VenueObject$`home_team_abbrev`
      self$`home_team_id` <- VenueObject$`home_team_id`
      self
    }
  )
)
